version: '3.8'

services:
  app:
    build: .
    restart: always
    networks:
      - my-network
    env_file:
      - .env
    ports:
      - "3000:3000"

  database:
    image: postgres
    restart: always
    networks:
      - my-network
    environment:
      POSTGRES_USER: reza
      POSTGRES_PASSWORD: reza
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  my-network:

volumes:
  db-data:
