stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: production

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - npm install --production
    - npm run start:prod
  only:
    - main
